### ISSUE TITLE
2.0 Roadmap

### ISSUE THREAD

**Issue by neokoenig** [neokoenig/RoomBooking#69]
Doing a complete rewrite for `2.x` which will break backwards compatibility. This may take some time.

**Testing and Continous Integration**
- [ ] Full TDD From the start
- [ ] Add Travis CI for lucee 4.5x and lucee 5.1.x + mySQL/postrgres possibly via Commandbox

**RESTFul API**
- [ ] Add Full JSONApi spec (http://jsonapi.org/) API with `/api/v1/` api root: this will enable people to build their own front ends if required
- [ ] Need Definitive list of endpoints

**User Accounts / Permissions / Settings**
- [ ] Move User password hashing to bCrypt
- [ ] Per User Time Zone Support
- [ ] Per User Language/Locale Support
- [ ] Add Better authentication system for 3rd party integration
- [ ] Look into AD/LDAP integration
- [ ] Soft Delete users should be fully delete-able/recoverable.

**Locations**
- [ ] Per Location Time Zone Support, so you could list rooms in buildings in multiple countries
- [ ] Add Location floorplans/attachments/images/capacity/type 
- [ ] Have more organisational units: building/floor/name|number?
- [ ] Better Calendar Filtering for Locations

**Events/Bookings**
- [ ] See how easy "slot based" booking is
- [ ] Add Full Repeating Rules Logic, possibly via Java Lib (Quartz etc)
- [ ] Improve contact details/notification system
- [ ] Ensure created events are owned by a user
- [ ] Add Search for "Next Available Slot / Find me a room with ...x "
- [ ] Full Text search for titles/descriptions (filter by past/future)
- [ ] Print friendly PDF Agendas
- [ ] Improve/Simplify Pending/Approved/Denied workflow

**Resources**
- [ ] Keep Resource booking concept? Or spin out further?
- [ ] Give resources their own calendars maybe, so you can see all activity for a specific piece of equipment

**General**
- [ ] Better Localisation/i8n 
- [ ] Store all logging/createdAt etc timestamps as UTC
- [ ] New/Better Install Process
- [ ] Upgrade FullCalendar JS -> 3.x
- [ ] New Theme via AdminLTE
- [ ] Add Digital Signage as a standalone self contained front end using an API key
- [ ] Add permission to show only users events
- [ ] Improve iCal/RSS etc

** Breaking Changes **
- [x] `/public/` is now the webroot (to help with docker images etc)
- [x] Drop List View (Full Calendar 3.0x has it)
- [x] Drop CF10 Compatibility: script support not up to snuff
- [x] Drop Custom Form fields (too complex, underused)
- [ ] Possibly drop ACF compatibility - won't have proper testing environment for it
- [ ] Different DB structure will mean probably no easy upgrade path from 1.x

** Framework **
- [x] CFWheels upgraded to 1.4.5: 2.x isn't ready yet, but 1.4.5 plus plugins will mean a smoother upgrade
- [x] Add RESTful Routing via ColdRoute plugin
- [x] Add Response Codes Plugin for wheels 2.x -> backport of http custom codes
- [ ] Add DBMigrate plugin to track proper DB migrations
